server:
  port: ${MS_API_GATEWAY_PORT}

spring:
  application:
    name: msvc-gateway


  # Activate API Gateway
  cloud:
    gateway:


      discovery:
        locator:
          enabled: true


      server:
        webmvc:


          # Define routes for api gateway

          routes:

            # Here should be each microservice routes
            - id: system-management
              uri: http://localhost:8090
              predicates:
                - Path=/api/v1/country/**

eureka:
  client:
    register-with-eureka: false