server:
  port: ${MS_CONTRACT_PORT}
spring:
  application:
    name: msvc-contract
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MS_DATASOURCE_URL}
    username: ${MS_USERNAME}
    password: ${MS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: foresttrade2025@gmail.com
    password: itgs jbvj tcdy brel
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          auth: true
          starttls:
            required: true
            enable: true



eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: ${MS_EUREKA_SERVER_DEFAULT_ZONE}

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /v3/api-docs


