server:
  port: ${MS_API_GATEWAY_PORT}

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      server:
        webmvc:
          routes:
            - id: system-management
              uri: http://localhost:8050
              predicates:
                - Path=/api/v1/country/**,/api/v1/city/**,/api/v1/economy-situation/**,/api/v1/sector/**,/api/v1/industry/**,/api/v1/issuer/**
            - id: market
              uri: http://localhost:8001
              predicates:
                - Path=/api/stocks
            - id: investor
              uri: http://localhost:8010
              predicates:
                - Path=/api/investor/**


eureka:
  client:
    register-with-eureka: false
