server:
  port: ${MS_SYSTEM_MANAGEMENT_PORT}

spring:
  application:
    name: msvc-system-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MS_DATASOURCE_URL}
    username: ${MS_USERNAME}
    password: ${MS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: andina_trading_mongo
      username: root
      password: davsancamros333
      authentication-database: admin

log:
  timezone: America/Bogota
  shared:
    root: C:/andina-logs

eureka:
  instance:
    hostname: ${MS_EUREKA_SERVER_HOSTNAME}
  client:
    service-url:
      defaultZone: ${MS_EUREKA_SERVER_DEFAULT_ZONE}