server:
  port: ${MS_EUREKA_SERVER_PORT}

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: ${MS_EUREKA_SERVER_HOSTNAME}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/