server:
  port: 8888

spring:
  application:
    name: config-server

  profiles:
    activate: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations