server:
  port: ${MS_CONFIG_SERVER_PORT}

spring:
  application:
    name: config-server

  profiles: { active: native }

  cloud:
    config:
      server:
        native:
          search-locations: ${MS_CONFIG_SERVER_CONFIGURATIONS_PATH}