CREATE DATABASE system_management_microservice;

USE system_management_microservice;

CREATE TABLE ECONOMY_SITUATION(
	
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    
    PRIMARY KEY (id)

);

CREATE TABLE COUNTRY(

	id INTEGER NOT NULL AUTO_INCREMENT,
    code VARCHAR(2) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    
    PRIMARY KEY (id)
);


CREATE TABLE CITY(

	id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(25) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    country_id INTEGER NOT NULL,
    economy_situation_id INTEGER NOT NULL,
    
    PRIMARY KEY (id),
    FOREIGN KEY (country_id) REFERENCES COUNTRY(id),
    FOREIGN KEY (economy_situation_id) REFERENCES ECONOMY_SITUATION(id)
    
);

CREATE TABLE SECTOR(

	id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    
    PRIMARY KEY (id)
    
);

CREATE TABLE INDUSTRY(

	id INTEGER NOT NULL AUTO_INCREMENT,
    sector_id INTEGER NOT NULL,
    name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    
    PRIMARY KEY (id),
    FOREIGN KEY (sector_id) REFERENCES SECTOR(id)
    
);


CREATE TABLE ISSUER (

  id  INTEGER AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL UNIQUE,
  ticker VARCHAR(10) NOT NULL UNIQUE,                
  country_id INTEGER NOT NULL,
  industry_id INTEGER NOT NULL,                
  website VARCHAR(200),
  notes VARCHAR(500) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  
  PRIMARY KEY (id),
  FOREIGN KEY (country_id) REFERENCES COUNTRY(id),
  FOREIGN KEY (industry_id) REFERENCES INDUSTRY(id)
  
);

CREATE TABLE DOCUMENT_TYPE(
	
    id INTEGER NOT NULL AUTO_INCREMENT,
    code VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
	country_id INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    
    PRIMARY KEY (id),
    FOREIGN KEY (country_id) REFERENCES COUNTRY(id)

);


CREATE TABLE BROKER (
  
	id INTEGER NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50),
    last_name VARCHAR(50) NOT NULL,
    document_type_id INTEGER NOT NULL,
    document_number VARCHAR(30) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    phone VARCHAR(15) NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
	PRIMARY KEY (id),
    FOREIGN KEY (document_type_id) REFERENCES DOCUMENT_TYPE(id),
     CONSTRAINT uk_broker_doctype_docnumber UNIQUE (document_type_id, document_number)
);